// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMQzX7-ImhCx35YYGEssC41AuMLn5nzE',
    appId: '1:216615461328:web:a5f338962a1642c1b619d5',
    messagingSenderId: '216615461328',
    projectId: 'sakani-3ddbb',
    authDomain: 'sakani-3ddbb.firebaseapp.com',
    storageBucket: 'sakani-3ddbb.firebasestorage.app',
    measurementId: 'G-8WFS5YR4WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHRtLC1fq8lcG5srVoZ055KaSM8kJNb3M',
    appId: '1:216615461328:android:19c95dd2ec890a69b619d5',
    messagingSenderId: '216615461328',
    projectId: 'sakani-3ddbb',
    storageBucket: 'sakani-3ddbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMY7cfCsab1NDprhVTiD7qQu_bcuhr30c',
    appId: '1:216615461328:ios:6689bc0f0e09dca2b619d5',
    messagingSenderId: '216615461328',
    projectId: 'sakani-3ddbb',
    storageBucket: 'sakani-3ddbb.firebasestorage.app',
    iosBundleId: 'com.example.sakani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaMQzX7-ImhCx35YYGEssC41AuMLn5nzE',
    appId: '1:216615461328:web:da29f7e89662ba8eb619d5',
    messagingSenderId: '216615461328',
    projectId: 'sakani-3ddbb',
    authDomain: 'sakani-3ddbb.firebaseapp.com',
    storageBucket: 'sakani-3ddbb.firebasestorage.app',
    measurementId: 'G-7RQ9HZBDES',
  );
}
